/**
 * Embed the teacher protocols (content/teacher/*.md — the owner's verbatim
 * instruction files, the source of truth) into a generated TS module so the
 * app can ship them as system prompts. Run after editing any protocol:
 *
 *   npm run embed-protocols
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const FILES: Record<string, string> = {
  id: 'indonesian-protocol.md',
  es: 'spanish-protocol.md',
  fr: 'french-protocol.md',
  it: 'italian-protocol.md',
};

const dir = join(__dirname, '..', 'content', 'teacher');
const out: string[] = [
  '// AUTO-GENERATED by scripts/embed-protocols.ts — do not edit by hand.',
  '// Source of truth: content/teacher/*.md (owner instruction files).',
  'export const PROTOCOLS: Record<string, string> = {',
];
for (const [lang, file] of Object.entries(FILES)) {
  const text = readFileSync(join(dir, file), 'utf8');
  out.push(`  ${lang}: ${JSON.stringify(text)},`);
  console.log(`${lang}: ${file} (${text.length} chars)`);
}
out.push('};', '');
writeFileSync(join(__dirname, '..', 'src', 'generated', 'teacher-protocols.ts'), out.join('\n'));
console.log('→ src/generated/teacher-protocols.ts');
